// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4sQQ4aiGMxcZ9ATmWFNRF3CFtcNUIvdc',
    appId: '1:669558649308:web:0369e37006753f8d791f19',
    messagingSenderId: '669558649308',
    projectId: 'chat-65854',
    authDomain: 'chat-65854.firebaseapp.com',
    storageBucket: 'chat-65854.firebasestorage.app',
    measurementId: 'G-DDQT2EQTS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJtUejUlGh4DhfxjPy7XIAjOTh5byXUGg',
    appId: '1:669558649308:android:7189d3a89dc88a57791f19',
    messagingSenderId: '669558649308',
    projectId: 'chat-65854',
    storageBucket: 'chat-65854.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn-LCX3jSdwp9qVnBa7CQTnfHNSppV_VM',
    appId: '1:669558649308:ios:9258eed7cb8e8d1d791f19',
    messagingSenderId: '669558649308',
    projectId: 'chat-65854',
    storageBucket: 'chat-65854.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn-LCX3jSdwp9qVnBa7CQTnfHNSppV_VM',
    appId: '1:669558649308:ios:9258eed7cb8e8d1d791f19',
    messagingSenderId: '669558649308',
    projectId: 'chat-65854',
    storageBucket: 'chat-65854.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4sQQ4aiGMxcZ9ATmWFNRF3CFtcNUIvdc',
    appId: '1:669558649308:web:1ef2aa2cb606d736791f19',
    messagingSenderId: '669558649308',
    projectId: 'chat-65854',
    authDomain: 'chat-65854.firebaseapp.com',
    storageBucket: 'chat-65854.firebasestorage.app',
    measurementId: 'G-5HZBQCCZG7',
  );
}
